### ISSUE TITLE
[Feature] Create schema for intermediate models

### ISSUE THREAD

**Issue by fivetran-avinash** [fivetran/dbt_recurly#12]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

It's best practice when it's necessary to materialize intermediate models as tables to have them live in their own schema so they don't overwhelm end users. [See an example in Zendesk.](https://github.com/fivetran/dbt_zendesk/blob/main/dbt_project.yml#L14)

### Are you interested in contributing this feature?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by fivetran-catfritz** [comment]
Addressed in PR #15
