### ISSUE TITLE
[BUG] Date_day should be date_week

### ISSUE THREAD

**Issue by fivetran-reneeli** [fivetran/dbt_recurly#13]
https://github.com/fivetran/dbt_recurly/blob/2da1316991d1498e85317150d2587c74ea358972/models/intermediate/int_recurly__account_rolling_totals.sql#L36

While looking through this I just realized I think this coalesce should be using date_week, not date_day!

**Comment by fivetran-joemarkiewicz** [comment]
@fivetran-catfritz is this issue able to be closed out? It seems the previous PR addressed the original issue.

**Comment by fivetran-catfritz** [comment]
@fivetran-joemarkiewicz Sorry about that. Yes #15 addresses this issue, so closing this out.
