### ISSUE TITLE
[Bug] Disable models for non-existent sources

### ISSUE THREAD

**Issue by benigls** [fivetran/dbt_recurly#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

In step 4 of the documentation

```
Step 4: Disable models for non-existent sources

vars:
  credit_payment_history: false # Disable if you do not have the credit_payment_history table
  subscription_add_on_history: false # Disable if you do not have the subscription_add_on_history table
  subscription_change_history: false # Disable if you do not have the subscription_change_history table
```

The `credit_payment_history` should be `recurly__using_credit_payment_history`

### Expected behavior

Skip credit_payment_history related tables

### dbt Project configurations

N/A

### Package versions

0.3.0

### What database are you using dbt with?

bigquery

### dbt Version

1.4.3

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @benigls thanks so much for raising this and catching the error in the README. 

You are completely correct that this should reflect the proper name of the variable. It looks like this was updated in the [source package documentation](https://github.com/fivetran/dbt_recurly_source#step-4-disable-models-for-non-existent-sources), but was missed here.

We can easily update this to reflect the correct variables. If you are open to creating a PR to address this fix I would be happy to review and merge into the next release. If not, no worries and I can make the proper updates. Let me know if you are interested in opening a PR!

**Comment by benigls** [comment]
Hi Joe! Thanks for reviewing the issue. Yup, I'm open to creating a PR to update the docs

**Comment by fivetran-joemarkiewicz** [comment]
Brilliant, thanks for being open to creating the PR. Let me know if you need any support and I will be happy to review as soon as possible once it is opened 😄

**Comment by fivetran-joemarkiewicz** [comment]
Thanks again for opening the PR to address this issue @benigls! The PR has since been merged and the latest release includes the updates. As such, I will close out this issue. Thanks again for raising this to our attention and being so quick to help to address the fix. 😄
