### ISSUE TITLE
[Bug] Test error on balance transactions

### ISSUE THREAD

**Issue by benigls** [fivetran/dbt_recurly#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

I encountered a test error in the `recurly__balance_transactions` model about duplicate `balance_transaction_id`. See the log below

```
07:47:04  Failure in test unique_recurly__balance_transactions_balance_transaction_id (models/recurly.yml)
07:47:04    Got 1644 results, configured to fail if != 0
07:47:04  
07:47:04    compiled Code at target/compiled/recurly/models/recurly.yml/unique_recurly__balance_transactions_balance_transaction_id.sql
```

Looking at one of the accounts in our recurly dashboard, I see that they have multiple failed transactions, see the photo below

<img width="868" alt="image 3" src="https://user-images.githubusercontent.com/9935276/222369223-c721c4b0-0904-4fc4-8b3c-cdac765d6d8b.png">

The failed transaction also appeared in the raw dataset inside the `transaction` table
```
-- query
select invoice_id, payment_method_card_type, created_at, status_code from raw.recurly.transaction where invoice_id = '...'
```
<img width="959" alt="image 4" src="https://user-images.githubusercontent.com/9935276/222370524-f0e1a6ba-7c55-4697-acf3-9dc76cf79ade.png">

I believe that the multiple failed transactions are causing the test failures because the `transaction` table is included in the `recurly__balance_transactions` model.

### Expected behavior

The package would handle multiple failed transactions with no test error.

### dbt Project configurations

recurly_database: raw
recurly_schema: recurly

recurly__using_credit_payment_history: false

### Package versions

- package: fivetran/recurly
  version: 0.3.0

### What database are you using dbt with?

bigquery

### dbt Version

1.4.3

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.

**Comment by fivetran-avinash** [comment]
Thanks for bringing this to our attention @benigls! [This is the same issue](https://github.com/fivetran/dbt_recurly_source/issues/8) that @dylanwatt was reporting on, but this is the repo where we'll be submitting the PR, so thanks for creating it here. We plan on making this fix by at least the coming sprint.

**Comment by fivetran-avinash** [comment]
Hi @benigls, we've deploye test fixes to our packages in our latest releases to [dbt_recurly](https://github.com/fivetran/dbt_recurly/releases/tag/v0.3.2). Try it out and let us know what you think!
