### ISSUE TITLE
[Feature] dbt.current_timestamp() functions should be dbt.current_timestamp_backcompat

### ISSUE THREAD

**Issue by fivetran-avinash** [fivetran/dbt_recurly#20]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

`dbt.current_timestamp` needs to be `dbt.current_timestamp_backcompat()` to ensure backwards compatibility for [Postgres and Snowflake for the latests dbt_utils upgrade](https://docs.getdbt.com/guides/migration/versions/upgrading-to-dbt-utils-v1.0
). 

 

### Are you interested in contributing this feature?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

### Anything else?

Models impacted are [here](https://github.com/fivetran/dbt_recurly/blob/main/models/recurly__account_overview.sql#L26) and [here](https://github.com/fivetran/dbt_recurly/blob/main/models/intermediate/int_recurly__account_cumulatives.sql#L16-L40).

**Comment by fivetran-jamie** [comment]
i wasn't aware of this macro 😮 guess this is something we need to roll out to other packages too?

**Comment by fivetran-avinash** [comment]
It's a handy one!
