### ISSUE TITLE
[Feature] Test Feature

### ISSUE THREAD

**Issue by fivetran-joemarkiewicz** [fivetran/dbt_recurly#27]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

This is a test to make sure we are able to accurately track the FR. I will close this issue once I can confirm it is tracked.

### Are you interested in contributing this feature?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by fivetran-reneeli** [comment]
Tracking now! Will close
